/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ClienteIndexRouteImport } from './routes/cliente/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ClienteNovoRouteImport } from './routes/cliente/novo'
import { Route as AppWorkflowRouteImport } from './routes/_app/workflow'
import { Route as AppThumbAiRouteImport } from './routes/_app/thumb-ai'
import { Route as AppPromptVaultRouteImport } from './routes/_app/prompt-vault'
import { Route as AppProjetosRouteImport } from './routes/_app/projetos'
import { Route as AppPedidosRouteImport } from './routes/_app/pedidos'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppCalendarioRouteImport } from './routes/_app/calendario'
import { Route as AppAssetsRouteImport } from './routes/_app/assets'
import { Route as ApiPublicSsrErrorsRouteImport } from './routes/api/public/ssr-errors'

const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ClienteNovoRoute = ClienteNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ClienteRoute,
} as any)
const AppWorkflowRoute = AppWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AppRoute,
} as any)
const AppThumbAiRoute = AppThumbAiRouteImport.update({
  id: '/thumb-ai',
  path: '/thumb-ai',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptVaultRoute = AppPromptVaultRouteImport.update({
  id: '/prompt-vault',
  path: '/prompt-vault',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosRoute = AppProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosRoute = AppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicSsrErrorsRoute = ApiPublicSsrErrorsRouteImport.update({
  id: '/api/public/ssr-errors',
  path: '/api/public/ssr-errors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/assets': typeof AppAssetsRoute
  '/calendario': typeof AppCalendarioRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/pedidos': typeof AppPedidosRoute
  '/projetos': typeof AppProjetosRoute
  '/prompt-vault': typeof AppPromptVaultRoute
  '/thumb-ai': typeof AppThumbAiRoute
  '/workflow': typeof AppWorkflowRoute
  '/cliente/novo': typeof ClienteNovoRoute
  '/cliente/': typeof ClienteIndexRoute
  '/api/public/ssr-errors': typeof ApiPublicSsrErrorsRoute
}
export interface FileRoutesByTo {
  '/assets': typeof AppAssetsRoute
  '/calendario': typeof AppCalendarioRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/pedidos': typeof AppPedidosRoute
  '/projetos': typeof AppProjetosRoute
  '/prompt-vault': typeof AppPromptVaultRoute
  '/thumb-ai': typeof AppThumbAiRoute
  '/workflow': typeof AppWorkflowRoute
  '/cliente/novo': typeof ClienteNovoRoute
  '/': typeof AppIndexRoute
  '/cliente': typeof ClienteIndexRoute
  '/api/public/ssr-errors': typeof ApiPublicSsrErrorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/_app/assets': typeof AppAssetsRoute
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/pedidos': typeof AppPedidosRoute
  '/_app/projetos': typeof AppProjetosRoute
  '/_app/prompt-vault': typeof AppPromptVaultRoute
  '/_app/thumb-ai': typeof AppThumbAiRoute
  '/_app/workflow': typeof AppWorkflowRoute
  '/cliente/novo': typeof ClienteNovoRoute
  '/_app/': typeof AppIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/api/public/ssr-errors': typeof ApiPublicSsrErrorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cliente'
    | '/assets'
    | '/calendario'
    | '/configuracoes'
    | '/pedidos'
    | '/projetos'
    | '/prompt-vault'
    | '/thumb-ai'
    | '/workflow'
    | '/cliente/novo'
    | '/cliente/'
    | '/api/public/ssr-errors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assets'
    | '/calendario'
    | '/configuracoes'
    | '/pedidos'
    | '/projetos'
    | '/prompt-vault'
    | '/thumb-ai'
    | '/workflow'
    | '/cliente/novo'
    | '/'
    | '/cliente'
    | '/api/public/ssr-errors'
  id:
    | '__root__'
    | '/_app'
    | '/cliente'
    | '/_app/assets'
    | '/_app/calendario'
    | '/_app/configuracoes'
    | '/_app/pedidos'
    | '/_app/projetos'
    | '/_app/prompt-vault'
    | '/_app/thumb-ai'
    | '/_app/workflow'
    | '/cliente/novo'
    | '/_app/'
    | '/cliente/'
    | '/api/public/ssr-errors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ClienteRoute: typeof ClienteRouteWithChildren
  ApiPublicSsrErrorsRoute: typeof ApiPublicSsrErrorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/cliente/novo': {
      id: '/cliente/novo'
      path: '/novo'
      fullPath: '/cliente/novo'
      preLoaderRoute: typeof ClienteNovoRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/_app/workflow': {
      id: '/_app/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AppWorkflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/thumb-ai': {
      id: '/_app/thumb-ai'
      path: '/thumb-ai'
      fullPath: '/thumb-ai'
      preLoaderRoute: typeof AppThumbAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prompt-vault': {
      id: '/_app/prompt-vault'
      path: '/prompt-vault'
      fullPath: '/prompt-vault'
      preLoaderRoute: typeof AppPromptVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projetos': {
      id: '/_app/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AppProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos': {
      id: '/_app/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AppPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/ssr-errors': {
      id: '/api/public/ssr-errors'
      path: '/api/public/ssr-errors'
      fullPath: '/api/public/ssr-errors'
      preLoaderRoute: typeof ApiPublicSsrErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAssetsRoute: typeof AppAssetsRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppPedidosRoute: typeof AppPedidosRoute
  AppProjetosRoute: typeof AppProjetosRoute
  AppPromptVaultRoute: typeof AppPromptVaultRoute
  AppThumbAiRoute: typeof AppThumbAiRoute
  AppWorkflowRoute: typeof AppWorkflowRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssetsRoute: AppAssetsRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppPedidosRoute: AppPedidosRoute,
  AppProjetosRoute: AppProjetosRoute,
  AppPromptVaultRoute: AppPromptVaultRoute,
  AppThumbAiRoute: AppThumbAiRoute,
  AppWorkflowRoute: AppWorkflowRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ClienteRouteChildren {
  ClienteNovoRoute: typeof ClienteNovoRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteNovoRoute: ClienteNovoRoute,
  ClienteIndexRoute: ClienteIndexRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ClienteRoute: ClienteRouteWithChildren,
  ApiPublicSsrErrorsRoute: ApiPublicSsrErrorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
